[build]
  command = "npm run build"
  publish = "out"

# No need for Next.js plugin with static export

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
